#######################################################################################
# Book settings
title : Previsor de reconhecimento
#author: scikit-learn developers
logo: ../figures/previsor_logo.png
copyright: "2022-2024"

# Information about where the book exists on the web
description: >-
  Previsor de reconhecimento federal
exclude_patterns:
  -  _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "figures"
  - "datasets"
  - "README.md"

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : -1

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_image

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issues_button           : true
  comments:
    hypothesis: true
  extra_footer: |
    <div>
      <h2>Resultados dos testes do previsor de reconhecimento federal de desastres</h2>
      <p>Os testes realizados para a construção deste previsor foram fundamentais para refinar a capacidade de previsão e melhorar o desempenho do modelo. 
      Para saber mais sobre o projeto, você pode consultar o capítulo inicial, onde explicamos detalhadamente a metodologia e os dados utilizados.</p>
      
      <p>Agradecemos especialmente à Enap pela realização do bootcamp em machine learning, que proporcionou o conhecimento necessário para o desenvolvimento deste trabalho.</p>
    </div>

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"
# notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    # Needed for plotly rendering:
    # https://jupyterbook.org/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/brunagmoura/PrevisorReconhecimento
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
#  colab_url: "https://colab.research.google.com" # Not working for now,
#  because it needs .ipynb
#  Disable thebe support since it does not start in the right folder, see
#  https://github.com/INRIA/scikit-learn-mooc/issues/669 for more details
#  thebe: true

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
